---
- hosts: 172.17.0.1
  remote_user: videk
  tasks:
  - name: download git project
    git: repo=https://github.com/matevzv/deployment-test.git dest=~/deploy/deployment-test

  - name: build docker file
    command: docker build -t controller -f Dockerfile.controller .
    args:
      chdir: ~/deploy/deployment-test

  - name: run docker image
    command: docker run --name controller_node controller

  - name: copy file from container
    command: docker cp controller_node:/test.log .
    args:
      chdir: ~/deploy/deployment-test

  - name: cleanup docker container controller_node
    command: "{{ item }}"
    with_items:
      - docker stop controller_node
      - docker rm controller_node

  - name: fetch test.log to out
    fetch:
      src: ~/deploy/deployment-test/test.log
      dest: ../out/test.log
      flat: yes
