---
- hosts: 1.2.3.4
  remote_user: videk
  tasks:
  - name: download git project
    git: repo=https://github.com/matevzv/deployment-test.git dest=~/deploy/deployment-test

  - name: build docker file
    command: docker build -t controller -f Dockerfile.controller .
    args:
      chdir: ~/deploy/deployment-test

  - name: run docker image
    command: docker run controller
    register: hello

  - debug: msg="{{ hello.stdout }}"

  - debug: msg="{{ hello.stderr }}"
