---
- hosts: localhost
  remote_user: matevz
  tasks:
  - name: download git project
    git: repo=https://github.com/matevzv/deployment-test.git dest=~/deploy/deployment-test

  - name: build docker file
    command: cd ~/deploy/deployment-test/Dockerfile.controller && docker build -t controller .

  - name: run docker image
    command: docker run controller
    register: hello

  - debug: msg="{{ hello.stdout }}"

  - debug: msg="{{ hello.stderr }}"
