---
- hosts: localhost
  remote_user: matevz
  tasks:
  - name: download git project
    git: repo=https://github.com/matevzv/deployment-test.git dest=/home/matevz/deploy/deployment-test

  - name: build docker file
    command: docker build -t controller -f /home/matevz/deploy/deployment-test/Dockerfile.controller .

  - name: run docker image
    command: docker run controller
    register: hello

  - debug: msg="{{ hello.stdout }}"

  - debug: msg="{{ hello.stderr }}"
