---
- hosts: edisons
  remote_user: matevz
  tasks:
  - name: download git project
    git: repo=https://github.com/matevzv/deployment-test.git dest=~/deploy/deployment-test

  - name: build docker file
    command: docker build -t deploymentsample ~/deploy/deployment-test

  - name: run docker image
    command: docker run -i -t deploymentsample
    register: hello

  - debug: msg="{{ hello.stdout }}"

  - debug: msg="{{ hello.stderr }}"
