FROM armv7/armhf-ubuntu:xenial

# File Author / Maintainer
MAINTAINER Matevz Vucnik

RUN apt-get update
RUN apt-get install -y python

ADD test-srv.py /root/hello/test-srv.py

WORKDIR /root/hello

# Run app
CMD python test-srv.py
