---
- hosts: 178.172.46.25
  remote_user: videk
  tasks:
  - name: download git project
    git: repo=https://github.com/matevzv/deployment-test.git dest=~/deploy/deployment-test

  - name: build docker file
    command: docker build -t node -f Dockerfile.nodes .
    args:
      chdir: ~/deploy/deployment-test

  - name: run docker image
    command: docker run --name hello_srv -d -p 8000:8000 node
    register: hello

  - debug: msg="{{ hello.stdout }}"

  - debug: msg="{{ hello.stderr }}"
