---
- hosts: 178.172.46.24
  remote_user: videk
  tasks:
  - name: cleanup docker containers
    register: hello
    command: "{{ item }}"
    with_items:
      - docker kill hello_srv
      - docker rm hello_srv

  - debug: msg="{{ hello.results[0].stdout_lines }}"
  - debug: msg="{{ hello.results[1].stdout_lines }}"
