---
- hosts: sna-lgtc
  remote_user: videk
  tasks:
  - name: cleanup docker containers
    command: bash -c "docker kill hello_srv"
    register: hello

  - debug: msg="{{ hello.stdout }}"

  - debug: msg="{{ hello.stderr }}"
